sudo: required # Required for apt-get build-dep
language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      dist: xenial
      env: MUMBLE_QT=qt5 MUMBLE_HOST=x86_64-linux-gnu

before_install:
    - ./scripts/travis-ci/before_install.bash

script:
    - ./scripts/travis-ci/script.bash
